users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /Users/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDO2l24krAYLYhuq7C/G1nkgjGxmRzPRTsuXBq/39bgw6YmwePkprlqppEwMnsrGV3/JSWi/HTTcJTD1J86cq5iEGXgHa+i513rGdhZr1aGpk1+6ytnzt1z6C15pCdGN62ap+Wn1tGQVUzxL+MB2BxE1FOEVaX0DBxAGBlhwy9g4tNud$4tNudoFp69AFWyPQRe69/S2yrwy6r4m4q6fMnTlzYbK17u0CzV1zE6ZP/VRVa4zsiNAvE7M3Vtd9LUH39y/T7SMxWjFxZuzaYtFbRy7YfzZE5omxQaEfeXN+ybbtE79J/LE6Y1b8WiGi+JcL4NhwJGu1VHj5m1NxT8Axu85upY2J aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl
  - wget