#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDO2l24krAYLYhuq7C/G1nkgjGxmRzPRTsuXBq/39bgw6YmwePkprlqppEwMnsrGV3/JSWi/HTTcJTD1J86cq5iEGXgHa+i513rGdhZr1aGpk1+6ytnzt1z6C15pCdGN62ap+Wn1tGQVUzxL+MB2BxE1FOEVaX0DBxAGBlhwy9g4tNudoFp69AFWyPQRe69/S2yrwy6r4m4q6fMnTlzYbK17u0CzV1zE6ZP/VRVa4zsiNAvE7M3Vtd9LUH39y/T7SMxWjFxZuzaYtFbRy7YfzZE5omxQaEfeXN+ybbtE79J/LE6Y1b8WiGi+JcL4NhwJGu1VHj5m1NxT8Axu85upY2J
    ssh_pwauth: false
disable_root: true
package_update: true
package_upgrade: true
packages:
  - apache2
  - php
  - php-mysql
  - adminer
  - mysql-client
  - curl
  - wget
write_files:
  - path: /var/www/html/index.html
    content: |
      <html>
      <head><title>Webserver</title></head>
      <body><h1>Webserver läuft!</h1></body>
      </html>
  - path: /var/www/html/info.php
    content: |
      <?php phpinfo(); ?>
  - path: /var/www/html/db.php
    content: |
      <?php
      $servername = "172.31.24.49"; // Private IP des DB-Servers
      $username = "admin";
      $password = "admin";
      $dbname = "MainDatabase";

      $conn = new mysqli($servername, $username, $password, $dbname);

      if ($conn->connect_error) {
          die("Connection failed: " . $conn->connect_error);
      }
      echo "Connected successfully";
      ?>
runcmd:
  - apt update
  - a2enconf adminer
  - systemctl restart apache2
  - echo "Cloud-Init Web erfolgreich abgeschlossen" > /home/ubuntu/init.log