#cloud-config
users: # Die Benutzer
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # Rechte
    groups: users, admin #Rechte
    home: /home/ubuntu # Home Pfad
    shell: /bin/bash # Shell
    ssh_authorized_keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDO2l24krAYLYhuq7C/G1nkgjGxmRzPRTsuXBq/39bgw6YmwePkprlqppEwMnsrGV3/JSWi/HTTcJTD1J86cq5iEGXgHa+i513rGdhZr1aGpk1+6ytnzt1z6C15pCdGN62ap+Wn1tGQVUzxL+MB2BxE1FOEVaX0DBxAGBlhwy9g4tNud$4tNudoFp69AFWyPQRe69/S2yrwy6r4m4q6fMnTlzYbK17u0CzV1zE6ZP/VRVa4zsiNAvE7M3Vtd9LUH39y/T7SMxWjFxZuzaYtFbRy7YfzZE5omxQaEfeXN+ybbtE79J/LE6Y1b8WiGi+JcL4NhwJGu1VHj5m1NxT8Axu85upY2J aws-key # SSH Key     
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClI5/25VtBL7ozv3bsPmFsAJBKcEn68tJx+tenoYgPEvUJI7T6dGxqlaP6901QRbzU27udS0JoV5ycDYLlKiJYFRQWVmK9hfNe5o7CJuDiuKK7A1q3FetEhx2qxuc0w/E6Ly2EuGz1baV2rJTFmhck86KlS58pKgRGQo/0q3ob+4AQZKR9a/J9/jxaSMtGZis7nrBLrpxF94FxPFOyNDhaJSHj8fsIOXeyVN8/IvWIEBD5BxSNu2WlKqIphPMAcb3iVBMfGsVSo75gMd/olagjdHe+0+mkX/ViS2GXlfMA2oyhc5KKOVdy/X0AoIsMTLtvpnrQMjxvLjJmX23yVKaF aws-key # SSH Key     
ssh_pwauth: false # Passwort Authentifikation
disable_root: false # Kein Root
package_update: true # Packages updaten
packages: # Die Packages
  - curl 
  - wget 
  - mariadb-server
runcmd:
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'rana123' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl enable mariadb
  - sudo systemctl restart mariadb.service